In [8]:
!pip install lxml

Requirement already satisfied: lxml in /opt/conda/lib/python3.6/site-packages (4.5.1)

In [95]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import lxml
for page in range(41):
    url = 'https://zan01.com/lotto649/history/{}'.format(page+1)

    res = requests.get(url=url)
    soup = BeautifulSoup(res.text,'html.parser')
    table = soup.select('html[lang="zh-tw"]')
    content = table[0].select('tbody')
    a = content[0].select('tr')
    c = a[0].text.replace(' ','').replace('\n','').split('\r')
    with open('./lo.txt','a') as outfile:
        for i in range(len(c)):
            try:
                if int(c[i]) < 109000056 and int(c[i]) > 104000001 :
                        outfile.write(str(c[i:i+4])+'|')
            except:
                pass
    print('page{} success!'.format(page+1))

page1 success!
page2 success!
page3 success!
page4 success!
page5 success!
page6 success!
page7 success!
page8 success!
page9 success!
page10 success!
page11 success!
page12 success!
page13 success!
page14 success!
page15 success!
page16 success!
page17 success!
page18 success!
page19 success!
page20 success!
page21 success!
page22 success!
page23 success!
page24 success!
page25 success!
page26 success!
page27 success!
page28 success!
page29 success!
page30 success!
page31 success!
page32 success!
page33 success!
page34 success!
page35 success!
page36 success!
page37 success!
page38 success!
page39 success!
page40 success!
page41 success!

In [110]:
with open('./lo.txt','r') as outfile:
    file = outfile.readline()

In [165]:
file

"['109000055', '2020-06-12', '483328013006', '27']|['109000054', '2020-06-09', '283547173608', '41']|['109000053', '2020-06-05', '032608490524', '19']|['109000052', '2020-06-02', '010622334825', '19']|['109000051', '2020-05-29', '314945403935', '41']|['109000050', '2020-05-26', '292538013305', '19']|['109000049', '2020-05-22', '130346071039', '29']|['109000048', '2020-05-19', '402733434432', '37']|['109000047', '2020-05-15', '454031061142', '43']|['109000046', '2020-05-12', '350108360511', '26']|['109000045', '2020-05-08', '090824102731', '33']|['109000044', '2020-05-05', '241949433617', '26']|['109000043', '2020-05-01', '184934480525', '45']|['109000042', '2020-04-28', '482916394336', '42']|['109000041', '2020-04-24', '390714171510', '45']|['109000040', '2020-04-21', '294701024533', '39']|['109000039', '2020-04-17', '333101214442', '22']|['109000038', '2020-04-14', '192633451721', '12']|['109000037', '2020-04-10', '134733484149', '01']|['109000036', '2020-04-07', '042744121807', '23']|['109000035', '2020-04-03', '024532434717', '34']|['109000034', '2020-03-31', '490626213634', '23']|['109000033', '2020-03-27', '490823021610', '41']|['109000032', '2020-03-24', '451210294116', '01']|['109000031', '2020-03-20', '134301084846', '29']|['109000030', '2020-03-17', '172928104743', '04']|['109000029', '2020-03-13', '143334224932', '31']|['109000028', '2020-03-10', '011234370425', '42']|['109000027', '2020-03-06', '161315300812', '45']|['109000026', '2020-03-03', '082817114210', '40']|['109000025', '2020-02-28', '021809484627', '25']|['109000024', '2020-02-25', '024847080144', '09']|['109000023', '2020-02-21', '131534393527', '31']|['109000022', '2020-02-18', '133142043735', '49']|['109000021', '2020-02-14', '331336352307', '09']|['109000020', '2020-02-11', '224309374623', '38']|['109000019', '2020-02-07', '194205152230', '31']|['109000018', '2020-02-04', '280323483727', '08']|['109000017', '2020-02-02', '171603333730', '29']|['109000016', '2020-02-01', '262034121002', '28']|['109000015', '2020-01-31', '161949322814', '01']|['109000014', '2020-01-30', '463524494106', '09']|['109000013', '2020-01-29', '141501040949', '32']|['109000012', '2020-01-28', '202803381302', '40']|['109000011', '2020-01-27', '093345122339', '24']|['109000010', '2020-01-26', '032928354147', '48']|['109000009', '2020-01-25', '051645134131', '09']|['109000008', '2020-01-24', '211807441338', '03']|['109000007', '2020-01-23', '134818304423', '37']|['109000006', '2020-01-21', '303817484422', '36']|['109000005', '2020-01-17', '204507420944', '08']|['109000004', '2020-01-14', '073834374720', '18']|['109000003', '2020-01-10', '380412331707', '11']|['109000002', '2020-01-07', '013816150508', '07']|['109000001', '2020-01-03', '181629193047', '10']|['108000112', '2019-12-31', '143826394710', '08']|['108000111', '2019-12-27', '172518324543', '05']|['108000110', '2019-12-24', '184831450949', '22']|['108000109', '2019-12-20', '281646212232', '24']|['108000108', '2019-12-17', '213827493109', '03']|['108000107', '2019-12-13', '124907263137', '17']|['108000106', '2019-12-10', '484118190803', '36']|['108000105', '2019-12-06', '242216234118', '39']|['108000104', '2019-12-03', '093611054515', '27']|['108000103', '2019-11-29', '213010244535', '22']|['108000102', '2019-11-26', '190810153645', '37']|['108000101', '2019-11-22', '032318262449', '32']|['108000100', '2019-11-19', '383505153047', '18']|['108000099', '2019-11-15', '441611032606', '31']|['108000098', '2019-11-12', '192725400131', '12']|['108000097', '2019-11-08', '094703264001', '15']|['108000096', '2019-11-05', '223713420940', '26']|['108000095', '2019-11-01', '414233231512', '11']|['108000094', '2019-10-29', '101241360322', '18']|['108000093', '2019-10-25', '032608361416', '41']|['108000092', '2019-10-22', '222317320642', '13']|['108000091', '2019-10-18', '364039322303', '49']|['108000090', '2019-10-15', '132138283735', '33']|['108000089', '2019-10-11', '073721171230', '49']|['108000088', '2019-10-08', '183421132607', '08']|['108000087', '2019-10-04', '482333102142', '41']|['108000086', '2019-10-01', '022015491209', '40']|['108000085', '2019-09-27', '371021263525', '04']|['108000084', '2019-09-24', '391820221602', '21']|['108000083', '2019-09-20', '083124342317', '25']|['108000082', '2019-09-17', '414048291218', '24']|['108000081', '2019-09-13', '150737270239', '43']|['108000080', '2019-09-10', '121720382903', '47']|['108000079', '2019-09-06', '431420192602', '23']|['108000078', '2019-09-03', '322511133348', '31']|['108000077', '2019-08-30', '420626444835', '07']|['108000076', '2019-08-27', '080401451047', '41']|['108000075', '2019-08-23', '420517432119', '16']|['108000074', '2019-08-20', '193542160127', '41']|['108000073', '2019-08-16', '314508073341', '39']|['108000072', '2019-08-13', '320541252136', '33']|['108000071', '2019-08-09', '041826134841', '33']|['108000070', '2019-08-06', '201049373801', '31']|['108000069', '2019-08-02', '484946340542', '14']|['108000068', '2019-07-30', '351221330424', '42']|['108000067', '2019-07-26', '483604414011', '49']|['108000066', '2019-07-23', '121437424735', '06']|['108000065', '2019-07-19', '123339261735', '10']|['108000064', '2019-07-16', '373130154839', '08']|['108000063', '2019-07-12', '193747181412', '30']|['108000062', '2019-07-09', '413720341711', '06']|['108000061', '2019-07-05', '324633113817', '15']|['108000060', '2019-07-02', '023933420411', '19']|['108000059', '2019-06-28', '332609131531', '10']|['108000058', '2019-06-25', '383136084520', '33']|['108000057', '2019-06-21', '303132122607', '13']|['108000056', '2019-06-18', '162905452733', '28']|['108000055', '2019-06-14', '103712242206', '03']|['108000054', '2019-06-11', '403942323106', '28']|['108000053', '2019-06-07', '381822273026', '45']|['108000052', '2019-06-04', '230506481943', '07']|['108000051', '2019-05-31', '210815363146', '18']|['108000050', '2019-05-28', '032240113836', '07']|['108000049', '2019-05-24', '192129391213', '41']|['108000048', '2019-05-21', '461807413210', '42']|['108000047', '2019-05-17', '451223022107', '10']|['108000046', '2019-05-14', '401509282743', '45']|['108000045', '2019-05-10', '372731331117', '12']|['108000044', '2019-05-07', '352902231443', '22']|['108000043', '2019-05-03', '060719323140', '15']|['108000042', '2019-04-30', '244947011904', '36']|['108000041', '2019-04-26', '372908244844', '06']|['108000040', '2019-04-23', '301408161835', '36']|['108000039', '2019-04-19', '292411450432', '49']|['108000038', '2019-04-16', '014123143639', '04']|['108000037', '2019-04-12', '322634464512', '14']|['108000036', '2019-04-09', '454410363746', '48']|['108000035', '2019-04-05', '283849294311', '22']|['108000034', '2019-04-02', '280540384741', '25']|['108000033', '2019-03-29', '011249032916', '04']|['108000032', '2019-03-26', '140624191338', '26']|['108000031', '2019-03-22', '371201474116', '36']|['108000030', '2019-03-19', '071648361747', '49']|['108000029', '2019-03-15', '051228203610', '15']|['108000028', '2019-03-12', '052207374045', '12']|['108000027', '2019-03-08', '310348111525', '36']|['108000026', '2019-03-05', '134212431621', '39']|['108000025', '2019-03-01', '270845401401', '34']|['108000024', '2019-02-26', '343842172206', '20']|['108000023', '2019-02-22', '484322204506', '11']|['108000022', '2019-02-19', '432404030132', '37']|['108000021', '2019-02-15', '400146440348', '02']|['108000020', '2019-02-12', '164530191129', '01']|['108000019', '2019-02-10', '471422080519', '24']|['108000018', '2019-02-09', '183019060820', '22']|['108000017', '2019-02-08', '421436133208', '05']|['108000016', '2019-02-07', '402107332941', '08']|['108000015', '2019-02-06', '172932233928', '12']|['108000014', '2019-02-05', '184513343049', '33']|['108000013', '2019-02-04', '243406323608', '49']|['108000012', '2019-02-03', '123736284024', '06']|['108000011', '2019-02-02', '224649350702', '41']|['108000010', '2019-02-01', '214132101720', '34']|['108000009', '2019-01-29', '143024482044', '31']|['108000008', '2019-01-25', '104515142003', '02']|['108000007', '2019-01-22', '203602423746', '29']|['108000006', '2019-01-18', '301004453905', '14']|['108000005', '2019-01-15', '124038204130', '10']|['108000004', '2019-01-11', '422231203413', '09']|['108000003', '2019-01-08', '391943212804', '18']|['108000002', '2019-01-04', '470820480706', '30']|['108000001', '2019-01-01', '422518242339', '48']|['107000108', '2018-12-28', '354423110719', '33']|['107000107', '2018-12-25', '270728322630', '44']|['107000106', '2018-12-21', '492141051934', '42']|['107000105', '2018-12-18', '151133080537', '03']|['107000104', '2018-12-14', '140609381949', '20']|['107000103', '2018-12-11', '071547212712', '48']|['107000102', '2018-12-07', '113336292034', '18']|['107000101', '2018-12-04', '031206201716', '14']|['107000100', '2018-11-30', '201445292705', '07']|['107000099', '2018-11-27', '273643444133', '31']|['107000098', '2018-11-23', '074337203421', '05']|['107000097', '2018-11-20', '043134443640', '20']|['107000096', '2018-11-16', '230730384911', '45']|['107000095', '2018-11-13', '073635424321', '10']|['107000094', '2018-11-09', '481215142204', '28']|['107000093', '2018-11-06', '260205383929', '07']|['107000092', '2018-11-02', '053241181647', '02']|['107000091', '2018-10-30', '284709033932', '07']|['107000090', '2018-10-26', '104123460833', '48']|['107000089', '2018-10-23', '422043091306', '21']|['107000088', '2018-10-19', '180749322042', '24']|['107000087', '2018-10-16', '460139492440', '33']|['107000086', '2018-10-12', '070604202112', '29']|['107000085', '2018-10-09', '131608234135', '21']|['107000084', '2018-10-05', '104244034709', '05']|['107000083', '2018-10-02', '084742163302', '14']|['107000082', '2018-09-28', '270737200102', '19']|['107000081', '2018-09-25', '394619254027', '06']|['107000080', '2018-09-21', '032945100511', '25']|['107000079', '2018-09-18', '454111363423', '43']|['107000078', '2018-09-14', '192937464536', '18']|['107000077', '2018-09-11', '442518141623', '41']|['107000076', '2018-09-07', '084437210214', '49']|['107000075', '2018-09-04', '100649420415', '12']|['107000074', '2018-08-31', '433734154612', '38']|['107000073', '2018-08-28', '081039421144', '27']|['107000072', '2018-08-24', '453107030939', '35']|['107000071', '2018-08-21', '311217283408', '01']|['107000070', '2018-08-17', '140319213548', '13']|['107000069', '2018-08-14', '491617251534', '05']|['107000068', '2018-08-10', '053648180716', '37']|['107000067', '2018-08-07', '194613253012', '05']|['107000066', '2018-08-03', '353004400643', '13']|['107000065', '2018-07-31', '312215352037', '14']|['107000064', '2018-07-27', '483505171219', '09']|['107000063', '2018-07-24', '244249322529', '12']|['107000062', '2018-07-20', '244512391309', '38']|['107000061', '2018-07-17', '413411262043', '09']|['107000060', '2018-07-13', '144642310221', '04']|['107000059', '2018-07-10', '114324093921', '07']|['107000058', '2018-07-06', '214728020332', '27']|['107000057', '2018-07-03', '113109342044', '10']|['107000056', '2018-06-29', '042737134130', '20']|['107000055', '2018-06-26', '440511372309', '24']|['107000054', '2018-06-22', '251130062607', '31']|['107000053', '2018-06-19', '093408374228', '15']|['107000052', '2018-06-15', '162846443025', '27']|['107000051', '2018-06-12', '023703151435', '29']|['107000050', '2018-06-08', '321709024031', '47']|['107000049', '2018-06-05', '262225410217', '16']|['107000048', '2018-06-01', '332628164942', '20']|['107000047', '2018-05-29', '112637144120', '02']|['107000046', '2018-05-25', '244222013206', '16']|['107000045', '2018-05-22', '294913412402', '45']|['107000044', '2018-05-18', '424111380136', '48']|['107000043', '2018-05-15', '131602431232', '24']|['107000042', '2018-05-11', '482535370411', '36']|['107000041', '2018-05-08', '084103372221', '46']|['107000040', '2018-05-04', '223047361033', '43']|['107000039', '2018-05-01', '084629493334', '19']|['107000038', '2018-04-27', '300448252726', '11']|['107000037', '2018-04-24', '101921353609', '49']|['107000036', '2018-04-20', '333210351446', '43']|['107000035', '2018-04-17', '074138164031', '39']|['107000034', '2018-04-13', '254612280140', '39']|['107000033', '2018-04-10', '324134074727', '09']|['107000032', '2018-04-06', '073425494731', '26']|['107000031', '2018-04-03', '363401320722', '08']|['107000030', '2018-03-30', '014405471343', '25']|['107000029', '2018-03-27', '131538402430', '44']|['107000028', '2018-03-23', '041341340932', '42']|['107000027', '2018-03-20', '300941372308', '31']|['107000026', '2018-03-16', '430314171646', '04']|['107000025', '2018-03-13', '202738142822', '19']|['107000024', '2018-03-09', '121838273015', '19']|['107000023', '2018-03-06', '130942111738', '29']|['107000022', '2018-03-02', '314801172512', '21']|['107000021', '2018-02-27', '032318280144', '10']|['107000020', '2018-02-23', '031541071816', '42']|['107000019', '2018-02-20', '123433404638', '07']|['107000018', '2018-02-19', '070919223649', '29']|['107000017', '2018-02-18', '074620280834', '10']|['107000016', '2018-02-17', '470517320333', '36']|['107000015', '2018-02-16', '044124072723', '17']|['107000014', '2018-02-15', '480737212241', '15']|['107000013', '2018-02-13', '101945043526', '38']|['107000012', '2018-02-09', '203021174512', '09']|['107000011', '2018-02-06', '412724431006', '49']|['107000010', '2018-02-02', '022610110143', '40']|['107000009', '2018-01-30', '310715233608', '30']|['107000008', '2018-01-26', '434734320723', '24']|['107000007', '2018-01-23', '122634280233', '44']|['107000006', '2018-01-19', '022616134822', '39']|['107000005', '2018-01-16', '362632083929', '23']|['107000004', '2018-01-12', '011445072240', '29']|['107000003', '2018-01-09', '243722100223', '42']|['107000002', '2018-01-05', '312913170444', '14']|['107000001', '2018-01-02', '461236020618', '47']|['106000108', '2017-12-29', '271512114720', '36']|['106000107', '2017-12-26', '201007240827', '19']|['106000106', '2017-12-22', '123118212037', '24']|['106000105', '2017-12-19', '034114311842', '02']|['106000104', '2017-12-15', '373124172719', '08']|['106000103', '2017-12-12', '281637194138', '10']|['106000102', '2017-12-08', '350508013410', '46']|['106000101', '2017-12-05', '371301434112', '49']|['106000100', '2017-12-01', '020305484228', '09']|['106000099', '2017-11-28', '470919461417', '29']|['106000098', '2017-11-24', '084504144110', '38']|['106000097', '2017-11-21', '432339282504', '41']|['106000096', '2017-11-17', '462839141902', '45']|['106000095', '2017-11-14', '244705251544', '45']|['106000094', '2017-11-10', '262435291015', '12']|['106000093', '2017-11-07', '220530480612', '41']|['106000092', '2017-11-03', '364308203323', '02']|['106000091', '2017-10-31', '462539360431', '02']|['106000090', '2017-10-27', '174038221102', '41']|['106000089', '2017-10-24', '021605290314', '32']|['106000088', '2017-10-20', '194203082618', '17']|['106000087', '2017-10-17', '012719061103', '05']|['106000086', '2017-10-13', '344605082344', '16']|['106000085', '2017-10-10', '280639303129', '33']|['106000084', '2017-10-06', '324145043728', '47']|['106000083', '2017-10-03', '153044253318', '38']|['106000082', '2017-09-29', '143603331621', '20']|['106000081', '2017-09-26', '191122141038', '42']|['106000080', '2017-09-22', '394749183543', '44']|['106000079', '2017-09-19', '401502181237', '39']|['106000078', '2017-09-15', '331603370811', '35']|['106000077', '2017-09-12', '362945230749', '14']|['106000076', '2017-09-08', '131929154208', '25']|['106000075', '2017-09-05', '332723131741', '02']|['106000074', '2017-09-01', '111436164005', '46']|['106000073', '2017-08-29', '312549180548', '44']|['106000072', '2017-08-25', '310104241928', '49']|['106000071', '2017-08-22', '101336044544', '05']|['106000070', '2017-08-18', '100712384735', '23']|['106000069', '2017-08-15', '272833134216', '11']|['106000068', '2017-08-11', '183709082702', '33']|['106000067', '2017-08-08', '062709463423', '20']|['106000066', '2017-08-04', '164515262739', '37']|['106000065', '2017-08-01', '304702214212', '31']|['106000064', '2017-07-28', '112213391838', '03']|['106000063', '2017-07-25', '112333300242', '07']|['106000062', '2017-07-21', '422412324702', '29']|['106000061', '2017-07-18', '214214132948', '11']|['106000060', '2017-07-14', '181925321626', '22']|['106000059', '2017-07-11', '193923061633', '07']|['106000058', '2017-07-07', '184930424044', '08']|['106000057', '2017-07-04', '272130283504', '42']|['106000056', '2017-06-30', '220832123036', '06']|['106000055', '2017-06-27', '113347494634', '38']|['106000054', '2017-06-23', '024142123408', '07']|['106000053', '2017-06-20', '123301442930', '19']|['106000052', '2017-06-16', '152636452101', '10']|['106000051', '2017-06-13', '360243041722', '40']|['106000050', '2017-06-09', '313724463226', '01']|['106000049', '2017-06-06', '483216251436', '12']|['106000048', '2017-06-02', '082307033130', '32']|['106000047', '2017-05-30', '073031191439', '40']|['106000046', '2017-05-26', '351608142119', '20']|['106000045', '2017-05-23', '021510222632', '42']|['106000044', '2017-05-19', '162115462823', '14']|['106000043', '2017-05-16', '060714462905', '24']|['106000042', '2017-05-12', '350902251822', '14']|['106000041', '2017-05-09', '161721402032', '15']|['106000040', '2017-05-05', '194909013418', '11']|['106000039', '2017-05-02', '273924362314', '13']|['106000038', '2017-04-28', '030131421932', '43']|['106000037', '2017-04-25', '411735323016', '26']|['106000036', '2017-04-21', '283922150523', '25']|['106000035', '2017-04-18', '252114393536', '18']|['106000034', '2017-04-14', '290203420423', '14']|['106000033', '2017-04-11', '402209473631', '08']|['106000032', '2017-04-07', '312337491932', '26']|['106000031', '2017-04-04', '053443173344', '04']|['106000030', '2017-03-31', '382224171825', '39']|['106000029', '2017-03-28', '324244223721', '38']|['106000028', '2017-03-24', '414939243645', '22']|['106000027', '2017-03-21', '321643442708', '07']|['106000026', '2017-03-17', '042517404436', '08']|['106000025', '2017-03-14', '323320391715', '21']|['106000024', '2017-03-10', '214148111235', '01']|['106000023', '2017-03-07', '224131061244', '02']|['106000022', '2017-03-03', '430220374816', '10']|['106000021', '2017-02-28', '194330141506', '31']|['106000020', '2017-02-24', '473538121641', '01']|['106000019', '2017-02-21', '483932150810', '43']|['106000018', '2017-02-17', '464923211606', '39']|['106000017', '2017-02-14', '103711212823', '24']|['106000016', '2017-02-10', '240711121526', '06']|['106000015', '2017-02-07', '193206182349', '21']|['106000014', '2017-02-03', '110225333029', '20']|['106000013', '2017-02-01', '044309473211', '44']|['106000012', '2017-01-31', '110433164628', '17']|['106000011', '2017-01-30', '261029194543', '20']|['106000010', '2017-01-29', '092203081412', '46']|['106000009', '2017-01-28', '322519203001', '02']|['106000008', '2017-01-27', '010549073531', '42']|['106000007', '2017-01-24', '330948011731', '49']|['106000006', '2017-01-20', '011605314118', '13']|['106000005', '2017-01-17', '402812043417', '07']|['106000004', '2017-01-13', '192527213814', '22']|['106000003', '2017-01-10', '371404461339', '31']|['106000002', '2017-01-06', '353212401443', '17']|['106000001', '2017-01-03', '184147492242', '45']|['105000111', '2016-12-30', '370607473538', '12']|['105000110', '2016-12-27', '402629103125', '02']|['105000109', '2016-12-23', '384223284108', '30']|['105000108', '2016-12-20', '353646012944', '06']|['105000107', '2016-12-16', '253642191134', '08']|['105000106', '2016-12-13', '362949393319', '06']|['105000105', '2016-12-09', '123842494428', '02']|['105000104', '2016-12-06', '464130322744', '42']|['105000103', '2016-12-02', '052534264940', '47']|['105000102', '2016-11-29', '032628384021', '42']|['105000101', '2016-11-25', '032842013722', '10']|['105000100', '2016-11-22', '342125440124', '19']|['105000099', '2016-11-18', '260618253424', '19']|['105000098', '2016-11-15', '083341432507', '06']|['105000097', '2016-11-11', '082807320222', '20']|['105000096', '2016-11-08', '221706491103', '44']|['105000095', '2016-11-04', '493802031728', '21']

In [166]:
file_list = file.split('|')

In [167]:
L = []
for data in file_list:
    L.append([data[2:11],data[15:25],data[29:41],data[45:47]])
del L[-1]

In [185]:
df = pd.DataFrame(L)
df[4],df[5],df[6],df[7],df[8],df[9] ='','','','','',''

In [186]:
for i in range(len(df)):
    df[4][i] = df[2][i][0:2]
    df[5][i] = df[2][i][2:4]
    df[6][i] = df[2][i][4:6]
    df[7][i] = df[2][i][6:8]
    df[8][i] = df[2][i][8:10]
    df[9][i] = df[2][i][10:12]

In [187]:
df[2][0][0:2]

'48'

In [189]:
df[10] = df[3]
df = df.drop([2,3],axis = 1)

In [195]:
df = df.rename(columns={0:'index' , 1: 'Date',4:'num1',5:'num2',6:'num3',7:'num4',8:'num5',9:'num6',10:'num7'})
df.index = pd.to_datetime(df['Date'],format = '%Y/%m/%d')

In [199]:
df

                index        Date num1 num2 num3 num4 num5 num6 num7
Date
2020-06-12  109000055  2020-06-12   48   33   28   01   30   06   27
2020-06-09  109000054  2020-06-09   28   35   47   17   36   08   41
2020-06-05  109000053  2020-06-05   03   26   08   49   05   24   19
2020-06-02  109000052  2020-06-02   01   06   22   33   48   25   19
2020-05-29  109000051  2020-05-29   31   49   45   40   39   35   41
2020-05-26  109000050  2020-05-26   29   25   38   01   33   05   19
2020-05-22  109000049  2020-05-22   13   03   46   07   10   39   29
2020-05-19  109000048  2020-05-19   40   27   33   43   44   32   37
2020-05-15  109000047  2020-05-15   45   40   31   06   11   42   43
2020-05-12  109000046  2020-05-12   35   01   08   36   05   11   26
2020-05-08  109000045  2020-05-08   09   08   24   10   27   31   33
2020-05-05  109000044  2020-05-05   24   19   49   43   36   17   26
2020-05-01  109000043  2020-05-01   18   49   34   48   05   25   45
2020-04-28  109000042  2020-04-28   48   29   16   39   43   36   42
2020-04-24  109000041  2020-04-24   39   07   14   17   15   10   45
2020-04-21  109000040  2020-04-21   29   47   01   02   45   33   39
2020-04-17  109000039  2020-04-17   33   31   01   21   44   42   22
2020-04-14  109000038  2020-04-14   19   26   33   45   17   21   12
2020-04-10  109000037  2020-04-10   13   47   33   48   41   49   01
2020-04-07  109000036  2020-04-07   04   27   44   12   18   07   23
2020-04-03  109000035  2020-04-03   02   45   32   43   47   17   34
2020-03-31  109000034  2020-03-31   49   06   26   21   36   34   23
2020-03-27  109000033  2020-03-27   49   08   23   02   16   10   41
2020-03-24  109000032  2020-03-24   45   12   10   29   41   16   01
2020-03-20  109000031  2020-03-20   13   43   01   08   48   46   29
2020-03-17  109000030  2020-03-17   17   29   28   10   47   43   04
2020-03-13  109000029  2020-03-13   14   33   34   22   49   32   31
2020-03-10  109000028  2020-03-10   01   12   34   37   04   25   42
2020-03-06  109000027  2020-03-06   16   13   15   30   08   12   45
2020-03-03  109000026  2020-03-03   08   28   17   11   42   10   40
...               ...         ...  ...  ...  ...  ...  ...  ...  ...
2015-03-31  104000031  2015-03-31   02   32   43   13   25   04   15
2015-03-27  104000030  2015-03-27   12   36   24   13   18   15   39
2015-03-24  104000029  2015-03-24   09   04   06   17   03   24   28
2015-03-20  104000028  2015-03-20   04   13   07   29   09   46   08
2015-03-17  104000027  2015-03-17   36   42   49   05   32   40   01
2015-03-13  104000026  2015-03-13   06   22   09   14   33   16   11
2015-03-10  104000025  2015-03-10   11   25   46   47   03   34   42
2015-03-06  104000024  2015-03-06   44   22   21   06   37   35   29
2015-03-03  104000023  2015-03-03   43   46   41   06   11   04   21
2015-02-27  104000022  2015-02-27   02   06   43   38   27   34   45
2015-02-24  104000021  2015-02-24   46   39   28   03   48   41   09
2015-02-23  104000020  2015-02-23   21   20   43   38   32   14   23
2015-02-22  104000019  2015-02-22   06   03   12   37   34   43   28
2015-02-21  104000018  2015-02-21   27   17   40   02   11   05   20
2015-02-20  104000017  2015-02-20   10   45   29   05   09   28   41
2015-02-19  104000016  2015-02-19   25   40   07   49   31   27   11
2015-02-18  104000015  2015-02-18   15   27   06   16   03   31   14
2015-02-17  104000014  2015-02-17   11   15   23   46   40   03   13
2015-02-13  104000013  2015-02-13   25   01   29   09   15   35   38
2015-02-10  104000012  2015-02-10   29   14   44   26   15   35   09
2015-02-06  104000011  2015-02-06   11   42   05   29   46   36   48
2015-02-03  104000010  2015-02-03   30   13   16   18   05   15   08
2015-01-30  104000009  2015-01-30   35   14   24   39   03   44   28
2015-01-27  104000008  2015-01-27   45   04   27   15   09   21   06
2015-01-23  104000007  2015-01-23   20   16   39   42   38   08   29
2015-01-20  104000006  2015-01-20   47   35   28   45   09   24   48
2015-01-16  104000005  2015-01-16   02   46   17   32   38   28   49
2015-01-13  104000004  2015-01-13   46   14   22   37   02   16   49
2015-01-09  104000003  2015-01-09   18   07   24   21   23   08   11
2015-01-06  104000002  2015-01-06   16   37   43   11   30   29   13

[602 rows x 9 columns]

In [200]:
df.to_csv('./lottery.csv')

In [201]:
df[df['num7']=='01']

                index        Date num1 num2 num3 num4 num5 num6 num7
Date
2020-04-10  109000037  2020-04-10   13   47   33   48   41   49   01
2020-03-24  109000032  2020-03-24   45   12   10   29   41   16   01
2020-01-31  109000015  2020-01-31   16   19   49   32   28   14   01
2019-02-12  108000020  2019-02-12   16   45   30   19   11   29   01
2018-08-21  107000071  2018-08-21   31   12   17   28   34   08   01
2017-06-09  106000050  2017-06-09   31   37   24   46   32   26   01
2017-03-10  106000024  2017-03-10   21   41   48   11   12   35   01
2017-02-24  106000020  2017-02-24   47   35   38   12   16   41   01
2016-08-02  105000068  2016-08-02   15   04   20   22   28   29   01
2016-01-08  105000003  2016-01-08   13   28   44   03   48   10   01
2015-03-17  104000027  2015-03-17   36   42   49   05   32   40   01